project:
  type: website
  output-dir: docs

website:
  title: "ushio-ecolab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - member.qmd
      - publication.qmd
      - joinlab.qmd
      - japanese.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



