---
title: "How to join the lab"
---

### Join our team!
We are seeking highly motivated students and postdocs with interests in **Environmental DNA**, **Ecosystem Dynamic**, **Community Ecology**, **Machine Learning**, and **Statistical Ecology**. Our primary research focus is on **Coastal Ecosystem**, but surrounding environments such as **Freshwater Ecosystems**, **Open Ocean**, and **Mangroves** are also our target. 

Please check our ongoing projects for more detail.

If you are interested in, please contact **ushio(at)ust.hk**.


### Graduate students
If you are a prospective student, please submit your application to the [Fok Ying Tung Graduate](https://fytgs.hkust.edu.hk/){target="_blank"} School of HKUST. For more information about the application process and requirements, please refer to the following websites:

- [Admission requirements](https://fytgs.hkust.edu.hk/admissions/Admission-to-Hong-Kong-Campus/submitting-an-application/admission-requirements){target="_blank"}
- [How to apply?](https://fytgs.hkust.edu.hk/admissions/Admission-to-Hong-Kong-Campus/submitting-an-application/how-to-apply){target="_blank"}
- [Student visa](https://fytgs.hkust.edu.hk/admissions/Admission-to-Hong-Kong-Campus/after-getting-an-offer/applying-student-visa){target="_blank"}

Several scholarship programs are available for graduate students:
- [Scholarships and Fees](https://fytgs.hkust.edu.hk/admissions/Admission-to-Hong-Kong-Campus/submitting-an-application/scholarships-and-fees){target="_blank"}

### Postdocs / Research assistants
We welcome applications from postdoctoral fellows and research assistants, although the availability of opportunities depends on our research funding. If you are interested in joining our lab in either of these roles, please contact us at **ushio(at)ust.hk**. Additionally, we are also open to hosting visiting scholars!

