---
title: "Publications"
---

See [Google Scholar](https://scholar.google.com/citations?user=GtIzgfYAAAAJ){target="_blank"} for the citation information.


# <font color="darkblue">Representative papers</font>
- **Ushio M**\*, Saito H, Tojo M, Nagano AJ (2023) An ecological network approach for detecting and validating influential organisms for rice growth. [_eLife_ 12:RP87202](https://doi.org/10.7554/eLife.87202)
- **Ushio M**\*, Sado T, Fukuchi T, Sasano S, Masuda R, Osada Y, Miya M\* (2023) Temperature sensitivity of the interspecific interaction strength of coastal marine fish communities. [_eLife_ 12:RP85795](https://doi.org/10.7554/eLife.85795) 
-  **Ushio M**\*, Watanabe K, Fukuda Y, Tokudome Y, Nakajima K* (2023) Computational capability of ecological dynamics. [_Royal Society Open Science_ 10:221614](https://doi.org/10.1098/rsos.221614)
-  **Ushio M**\* (2022) Interaction capacity as a potential driver of community diversity. [_Proceedings of the Royal Society B_ 289: 20212690](https://doi.org/10.1098/rspb.2021.2690)
<!--
-  **Ushio M**\* (2019) Use of a filter cartridge combined with intra-cartridge bead-beating improves detection of microbial DNA from water samples. [_Methods in Ecology and Evolution_ 10 (8):1142–1156](https://doi.org/10.1111/2041-210X.13204)

-  **Ushio M**\*, Murakami H, Masuda R, Sado T, Miya M, Sakurai S, Yamanaka H, Minamoto T, Kondoh M (2018) Quantitative monitoring of multispecies fish environmental DNA using high-throughput sequencing.  [_Metabarcoding & Metagenomics_ 2: e23297](https://dx.doi.org/10.3897/mbmg.2.23297)
-->
-  **Ushio M**\*, Hsieh CH, Masuda R, Deyle RE, Ye H, Chang CW, Sugihara G, Kondoh M\* (2018) Fluctuating interaction network and time-varying stability of a natural fish community. [_Nature_ 554 (7692): 360–363](https://doi.org/10.1038/nature25504)
-  **Ushio M**\*, Fukuda H, Inoue T, Makoto K, Kishida O, Sato K, Murata K, Nikaido M, Sado T, Sato Y, Takeshita M, Iwasaki W, Yamanaka H, Kondoh M, Miya M\* (2017) Environmental DNA enables detection of terrestrial mammals from forest pond water. [_Molecular Ecology Resources_ 17: e63–e75](https://dx.doi.org/10.1111/1755-0998.12690) 
-  **Ushio M**\*, Aiba S-I, Takeuchi Y, Iida Y, Matsuoka S, Repin R, Kitayama K (2017) Plant-soil feedbacks and the dominance of conifers in a tropical montane forest in Borneo. [_Ecological Monographs_ 87 (1): 105–129](https://dx.doi.org/10.1002/ecm.1236)


<br>

# Published / Preprints

----------

### <font color="gray">Preprints</font>

----------

<font color="gray">

- **Liu C**\*, Xia F, Hirayama IT, Yagi G, **Ushio M**\* (2025) Epi-eDNA: From methylation signal detection to functional ecological monitoring. [_EcoEvoRxiv_](https://doi.org/10.32942/X2R340)  

- **Ushio M**\*, Saito H, Shimono Y, Okada K, Ozawa R, Shiojiri K,  Takabayashi J (2025) Contrasting ecological communities in rice paddy fields under conventional and no-fertilizer farming practices. [_bioRxiv_](https://doi.org/10.1101/2025.08.12.669982)  

- Gao et al. (2024) Diversity and distinctive traits of the global RNA virome in urban environments. [Available at SSRN](https://dx.doi.org/10.2139/ssrn.4871972)

- Osada Y\*, **Ushio M**, Kondoh M (2023) A unified framework for nonparametric causality detection. [_bioRxiv_](https://doi.org/10.1101/2023.04.20.537743)

</font>

## In press / early view
1. **Ushio M**\*, Ozawa S, Oka S-I, Sado T, **Kisero RO**, Porter L, Matrai E, Miya M (in press)  
$\mu$Ceta: a set of cetacean-specific primers for environmental DNA metabarcoding with minimal amplification of non-target vertebrates. _Environmental DNA_  


## 2025
1. **Ushio M**\*, Nakajima K (2025)  
    Reservoir computing: theory and its potential applications in ecology. (in Japanese) [_Japanese Journal of Ecology_ 74:229-238](https://doi.org/10.18960/seitai.74.2_229)
1. Lee SS, Lee HS, Xu Z, **Ushio M**, Zhang X, Liu H\* (2025)  
    Community stability of free-living and particle-attached bacteria in coastal waters across four seasons: insights from 9.5 years of weekly sampling. [_Marine Pollution Bulletin_ 216:117990](https://doi.org/10.1016/j.marpolbul.2025.117990)
1. Miki T\*, Chang CW, Ke PJ, Telschow A, Tsai CH, **Ushio M**, Hsieh CH (2025)  
    How to quantify interaction strengths? A critical rethinking of the interaction Jacobian and evaluation methods for non-parametric inference in time series analysis. [_Physica D: Nonlinear Phenomena_ 134613](https://doi.org/10.1016/j.physd.2025.134613)
1. Jiang L*, **Ushio M**, Imai N, Sugau J, Kitayama K (2025)  
    Changes of bacterial versus fungal community composition along a forest degradation gradient of logged-over tropical rain forests, and their consequences on soil enzyme activities in Malaysian Borneo. [_Plant and Soil_ 510:541-563](https://doi.org/10.1007/s11104-024-06939-6)
1.  Fukasawa Y\*, Kimura S, Kominami Y, Takagi M, Matsukura K, Makoto K, Suzuki SN, Takemoto S, Tanaka N, Jomura M, Kadowaki K, **Ushio M**, Kinuura H, Yamashita S (2025)  
    Oak wilt disease may reduce the initial decay rate of dead Quercus serrata stems by altering fungal communities in the wood. [_Environmental Microbiology_ 27:e70026](https://doi.org/10.1111/1462-2920.70026)


## 2024
1.  Oka S-I\*, Sado T, **Ushio M**, Miya M\* (2024)  
    Assessing the impact of tidal changes on fish environmental DNA metabarcoding in temperate and tropical coastal regions of Japan. [_Metabarcoding & Metagenomics_ 8:e135461](https://doi.org/10.3897/mbmg.8.135461)
1. Atsumi K, Nishida Y, **Ushio M**, Nishi H, Genroku T, Fujiki S* (2024)  
    Boosting biodiversity monitoring using smartphone-driven, rapidly accumulating citizen data. [_eLife_ 13:RP93694](https://doi.org/10.7554/eLife.93694)
1. Maehara K, Iwachido Y, Katsuhara H, Tomitaka M, Seto K, **Ushio M**, Kagami M, Sasaki T\* (2024)  
    Plant and soil microbial community assembly processes across urban vacant lots. [_Journal of Vegetation Science_ 35:e13262](https://doi.org/10.1111/jvs.13262)
1. Sugiyama Y\*, Matsuoka S, Shimono Y, **Ushio M**, Doi H (2024)  
    Do water fungal environmental DNA assemblages reflect the surrounding terrestrial sporocarp communities? [_Fungal Ecology_ 67:101311](https://doi.org/10.1016/j.funeco.2023.101311)
    

## 2023
1. Fujita H\*, **Ushio M**, Suzuki K, Abe MS, Yamamichi M, Okazaki Y, Canarini A, Hayashi I, Fukushima K, Fukuda S, Kiers ET, Toju H\* (2023)  
    Metagenomic analysis of ecological niche overlap and community collapse in microbiome dynamics. [_Frontiers in Microbiology_ 14:1261137](https://doi.org/10.3389/fmicb.2023.1261137)
1. Sakata A\*, Sado T, Oka S-I, **Ushio M**, Miya M\* (2023)  
   Collection of environmental DNA from stemflow for monitoring arboreal biodiversity: preliminary validation using lichens. [_MethodsX_ 11:102448](https://doi.org/10.1016/j.mex.2023.102448)
1.  Maxime M\*, **Ushio M**, Sakai S. (2023)  
    The effects of the floral infection by a bacterial pathogen in a dioecious plant, _Mallotus japonicus_ (Euphorbiaceae). [_Population Ecology_  65:232-239](https://doi.org/10.1002/1438-390X.12110)
1. **Ushio M**\*, Saito H, Tojo M, Nagano AJ (2023)  
    An ecological network approach for detecting and validating influential organisms for rice growth. [_eLife_ 12:RP87202](https://doi.org/10.7554/eLife.87202)
1. **Ushio M**\*, Sado T, Fukuchi T, Sasano S, Masuda R, Osada Y, Miya M\* (2023)  
    Temperature sensitivity of the interspecific interaction strength of coastal marine fish communities. [_eLife_ 12:RP85795](https://doi.org/10.7554/eLife.85795)
1.  Yoneya K\*, **Ushio M**, Miki T (2023)  
    Non-destructive collection and metabarcoding of arthropod environmental DNA remained on a terrestrial plant. [_Scientific Reports_ 13:7125](https://doi.org/10.1038/s41598-023-32862-4)
1.  Jiang L\*, **Ushio M**, Kitayama K (2023)  
    Changes of soil chemical properties, microbial biomass and enzymatic activities along a gradient of forest degradation in logged over tropical rain forests, Borneo. [_Plant and Soil_ 485:525–536](https://doi.org/10.1007/s11104-022-05848-w)
1.  **Ushio M**\*, Watanabe K, Fukuda Y, Tokudome Y, Nakajima K\* (2023)  
    Computational capability of ecological dynamics. [_Royal Society Open Science_ 10:221614](https://doi.org/10.1098/rsos.221614)
3.  Fujita H\*, **Ushio M**, Suzuki K, Abe MS, Yamamichi M, Okazaki Y, Canarini A, Hayashi I, Fukushima K, Fukuda S, Kiers ET, Toju H\* (2023)  
    Facilitative interaction networks in experimental microbial community dynamics. [_Frontiers in Microbiology_ 14:1153952](https://doi.org/10.3389/fmicb.2023.1153952)
5.  Fujita H\*, **Ushio M**, Suzuki K, Abe MS, Yamamichi M, Iwayama K, Canarini A, Hayashi I, Fukushima K, Fukuda S, Kiers ET, Toju H\* (2023)  
    Alternative stable states, nonlinear behavior, and predictability of microbiome dynamics. [_Microbiome_ 11:63](https://doi.org/10.1186/s40168-023-01474-5)
1.  Fukasawa Y\*, Akai D, **Ushio M**, Takehi T (2023)  
    Electrical potentials in the ectomycorrhizal fungus Laccaria bicolor after a rainfall event. [_Fungal Ecology_ 63:101229](https://doi.org/10.1016/j.funeco.2023.101229)
1.  Tsujii Y\*, Sakai S, **Ushio M**, Aiba S-I, Kitayama K (2023)  
    Variations in the reproductive cycle of Bornean montane tree species along elevational gradients on ultrabasic and non-ultrabasic soils. [_Biotropica_ 55 (1):210–220](https://doi.org/10.1111/btp.13177)



## <font color="gray">Before joining HKUST</font>

## 2022
1.  **Ushio M**\*, Furukawa S, Murakami H, Masuda R, Nagano AJ\* (2022)  
    An efficient early-pooling protocol for environmental DNA metabarcoding. [_Environmental DNA_ 4 (6):1212–1228](https://doi.org/10.1002/edn3.337)
3.  Inoue N\*, Sato M, Furuichi N, Imaizumi T, **Ushio M** (2022)  
    The relationship between eDNA density distribution and current fields around an artificial reef in the waters of Tateyama Bay, Japan. [_Metabarcoding & Metagenomics_ 6:e87415](https://doi.org/10.3897/mbmg.6.87415)
5.  Fukasawa Y\*, Matsukura K, Stephan JG, Makoto K, Suzuki SN, Kominami Y, Takagi M, Tanaka N, Takemoto S, Kinuura H, Okano K, Song Z, Jomura M, Kadowaki K, Yamashita S, **Ushio M** (2022)  
    Patterns of community composition and diversity in latent fungi of living _Quercus serrata_ trunks across a range of oak wilt prevalence and climate variables in Japan. [_Fungal Ecology_ 59:101095](https://doi.org/10.1016/j.funeco.2021.101095)
7.  Elvira NJ, **Ushio M**, Sakai S\* (2022)  
    Are microbes growing on flowers evil? Effects of old flower microbes on fruit set in a wild ginger with one-day flowers, _Alpinia japonica_ (Zingiberaceae). [_Metabarcoding & Metagenomics_ 6:e84331](https://doi.org/10.3897/mbmg.6.84331)
9.  Maxime M\*, **Ushio M**, Sakai S. (2022)  
    Contrasting microbial communities on male and female flowers of a dioecious plant, _Mallotus japonicus_ (Euphorbiaceae). [_Environmental DNA_ 4 (3):565–579](https://doi.org/10.1002/edn3.271)
11.  **Ushio M**\* (2022)
    Interaction capacity as a potential driver of community diversity. [_Proceedings of the Royal Society B_ 289:20212690](https://doi.org/10.1098/rspb.2021.2690)


## 2021
1.  Chang CW, Miki T, **Ushio M**, Ke PJ, Lu HP, Shiah FK, Hsieh CH\* (2021)  
    Reconstructing large interaction networks from empirical time series data. [_Ecology Letters_ 24 (12):2763–2774](https://doi.org/10.1111/ele.13897)
3.  Sato M\*, Inoue N, Nambu R, Furuich N, Imaizumi T, **Ushio M** (2021)  
    Quantitative assessment of multiple fish species around artificial reefs using environmental DNA metabarcoding. [_Scientific Reports_ 11:19477](https://doi.org/10.1038/s41598-021-98926-5)
5.  Matsuoka S\*, Sugiyama Y, Shimono Y, **Ushio M**, Doi H (2021)  
    Evaluation of seasonal dynamics of fungal DNA assemblages in a flow-regulated stream in a restored forest using eDNA metabarcoding. [_Environmental Microbiology_ 23 (8):4797–4806](https://doi.org/10.1111/1462-2920.15669)
7.  Doi H\*, Yasuhara M\*, **Ushio M**\* (2021)  
    Causal analysis of the temperature impact on deep-sea biodiversity. [_Biology Letters_ 17 (7):20200666](https://doi.org/10.1098/rsbl.2020.0666)
9.  Shiragaki T, Inoue T, Fukuda H, **Ushio M**, Kusakabe M, Okano T, Takasu H\* (2021)  
    A pilot study investigating fish species composition using environmental DNA in marine sediment (in Japanese). [_Journal of Japan Society on Water Environment_ 44 (4):79–84](https://doi.org/10.2965/jswe.44.79)
11.  Kawatsu K, **Ushio M**, van Veen F, Kondoh M\* (2021)  
    Are networks of trophic interactions sufficient for understanding the dynamics of multi-trophic communities? Analysis of a tri-trophic insect food-web time-series. [_Ecology Letters_ 24 (3):543–552](https://doi.org/10.1111/ele.13672)
13.  Kitayama K*, **Ushio M**\*, Aiba S-I (2021)  
    Temperature is a dominant driver of distinct annual seasonality of leaf litter production of equatorial tropical rain forests. [_Journal of Ecology_ 109 (2):727–736](https://doi.org/10.1111/1365-2745.13500)


## 2020
1.  Yonezawa S, **Ushio M**\*, Yamanaka H, Miya M, Takayanagi A, Isagi Y\* (2020)  
    Environmental DNA metabarcoding reveals the presence of a small, quick-moving, nocturnal water shrew in a forest stream. [_Conservation Genetics_ 21 (6):1079–1084](https://doi.org/10.1007/s10592-020-01310-5)
1.  Tsuji S\*, Shibata N, Sawada H, **Ushio M** (2020)  
    Quantitative evaluation of intraspecific genetic diversity in a natural fish population using environmental DNA analysis. [_Molecular Ecology Resources_ 20 (5):1323–1332](https://doi.org/10.1111/1755-0998.13200)
1.  Tsuji, S\*, Maruyama A, Miya M, **Ushio M**, Sato H, Minamoto T, Yamanaka H (2020)  
    Environmental DNA analysis shows high potential as a tool for estimating intraspecific genetic diversity in a wild fish population. [_Molecular Ecology Resources_ 20 (5):1248–1258](https://doi.org/10.1111/1755-0998.13165)
1.  Cai J, Hodoki Y, **Ushio M**, Nakano S-I\* (2020)  
    Influences of potential grazers on picocyanobacteria abundances in Lake Biwa revealed by empirical dynamic modeling. [_Inland Water_ 10 (3):386–396](https://doi.org/10.1080/20442041.2020.1711682)
1.  **Ushio M**\* (2020) [Special Feature]  
    Idea paper: Predicting culturability of microbes from population dynamics under field conditions. [_Ecological Research_ 35 (4):586–590](https://doi.org/10.1111/1440-1703.12104)
1.  Nishio H\*, Buzas DM, Nagano AJ, Iwayama K, **Ushio M**, Kudoh H\* (2020)   
    Repressive chromatin modification underpins the long-term expression trend of a perennial flowering gene in nature. [_Nature Communications_ 11:2065](https://doi.org/10.1038/s41467-020-15896-4)
1.  Shirouzu T\*, Matsuoka S, Doi H, Nagata N, **Ushio M**, Hosaka K (2020) 
    Complementary molecular methods reveal a comprehensive phylogenetic diversity with integrating invisible lineages of early-diverged mushrooms. [_Scientific Reports_ 10:3057](https://doi.org/10.1038/s41598-020-59620-0)
1.  **Ushio M**\*, Osada Y, Kumagai T, Kume T, Pungga RS, Nakashizuka T, Itioka T, Sakai S* (2020)
    Dynamic and synergistic influences of air temperature and rainfall on general flowering in a Bornean lowland tropical forest. [_Ecological Research_ 35 (1):17–29](https://doi.org/10.1111/1440-1703.12057)
1.  Tsuji S\*, Miya M, **Ushio M**, Sato H, Minamoto T, Yamanaka H (2020)  
    Evaluating intraspecific genetic diversity using environmental DNA and denoising approach: A case study using tank water. [_Environmental DNA_ 2 (1):42–52](https://doi.org/10.1002/edn3.44)


## 2019
1.  **Ushio M**\* (2019)  
    Use of a filter cartridge combined with intra-cartridge bead-beating improves detection of microbial DNA from water samples. [_Methods in Ecology and Evolution_ 10 (8):1142–1156](https://doi.org/10.1111/2041-210X.13204)</span>
1.  Nakagawa M\*, **Ushio M**, Kume T, Nakashizuka T (2019)  
    Seasonal and long-term patterns in litterfall in a Bornean tropical rainforest. [_Ecological Research_ 34 (1):31–39](https://doi.org/10.1111/1440-1703.1003)


## 2018
1.  Toju H\*, Peay KG, Yamamichi M, Narisawa K, Hiruma K, Naito K, Fukuda S, **Ushio M**, Nakaoka S, Onoda Y, Yoshida K, Schlaeppi K, Bai Y, Sugiura R, Ichihashi Y, Minamisawa K, Kiers ET (2018)  
    Core microbiomes for sustainable agroecosystems. [_Nature Plants_ 4:247–257](https://dx.doi.org/10.1038/s41477-018-0139-4)
3.  **Ushio M**\*, Murata K, Sado T, Nishiumi I, Takeshita M, Iwasaki W, Miya M\* (2018)  
    Demonstration of the potential of environmental DNA as a tool for the detection of avian species. [_Scientific Reports_ 8:4493](https://dx.doi.org/10.1038/s41598-018-22817-5)
1.  **Ushio M**\*, Murakami H, Masuda R, Sado T, Miya M, Sakurai S, Yamanaka H, Minamoto T, Kondoh M (2018) 
    Quantitative monitoring of multispecies fish environmental DNA using high-throughput sequencing.  [_Metabarcoding & Metagenomics_ 2:e23297](https://dx.doi.org/10.3897/mbmg.2.23297)
1.  **Ushio M**\*, Hsieh CH, Masuda R, Deyle RE, Ye H, Chang CW, Sugihara G, Kondoh M\* (2018)  
    Fluctuating interaction network and time-varying stability of a natural fish community. [_Nature_ 554 (7692):360–363](https://doi.org/10.1038/nature25504)



## 2017
1.  Aiba S-I\*, Miyamoto K, **Ushio M**, Aoyagi R, Sawada Y (2017)  
    Mechanism determining conifer dominance in terrestrial ecosystems: A synthesis (in Japanese). [_Japanese Journal of Ecology_ 67 (3):355–360](https://doi.org/10.18960/seitai.67.3_355)
3.  **Ushio M**\* (2017)  
    Root morphology, mycorrhizal fungi and nitrogen fixation capacity of Podocarpaceae and Araucariaceae (in Japanese). [_Japanese Journal of Ecology_ 67 (3):339–345](https://doi.org/10.18960/seitai.67.3_339)
5.  **Ushio M**\*, Fukuda H, Inoue T, Makoto K, Kishida O, Sato K, Murata K, Nikaido M, Sado T, Sato Y, Takeshita M, Iwasaki W, Yamanaka H, Kondoh M, Miya M\* (2017)  
    Environmental DNA enables detection of terrestrial mammals from forest pond water. [_Molecular Ecology Resources_ 17 (6):e63–e75](https://dx.doi.org/10.1111/1755-0998.12690) 
7.  Chang CW\*, **Ushio M**\*, Hsieh CH\* (2017)  
    Empirical dynamic modeling for beginners. [_Ecological Research_ 32 (6):785–796](https://doi.org/10.1007/s11284-017-1469-9)
9.  Ishige T, Miya M, **Ushio M**, Sado T, Ushioda M, Yonechi R, Lagan P, Matsubayashi H\* (2017)  
    Tropical-forest mammals as detected by environmental DNA at natural saltlicks. [_Biological Conservation_ 210:281–285](https://doi.org/10.1016/j.biocon.2017.04.023)
11.  Tsuji S\*, **Ushio M**, Sakurai S, Minamoto T, Yamanaka H (2017)   
    Water temperature-dependent degradation of environmental DNA and its relation to bacterial abundance. [_PLoS ONE_ 12 (4) e0176608](https://doi.org/10.1371/journal.pone.0176608)
13.  **Ushio M**\*, Aiba S-I, Takeuchi Y, Iida Y, Matsuoka S, Repin R, Kitayama K (2017)  
    Plant-soil feedbacks and the dominance of conifers in a tropical montane forest in Borneo. [_Ecological Monographs_ 87 (1):105–129](https://dx.doi.org/10.1002/ecm.1236)
14.  Koyama K\*, Yamamoto K, **Ushio M** (2017)  
    A lognormal distribution of the lengths of terminal twigs on self-similar branches of elm trees. [_Proceedings of the Royal Society B_ 284:20162395](https://dx.doi.org/10.1098/rspb.2016.2395)



## 2016
1.  Sakai S\*, Keong CY, Koizumi M, Kishimoto-Yamada K, Takano KT, Ichikawa M, Samejima H, Kato Y, Soda R, **Ushio M**, Saizen I, Nakashizuka T, Itioka T (2016)  
    Social and ecological factors associated with the use of non-timber forest products by people in rural Borneo. [_Biological Conservation_ 204:340–349](https://dx.doi.org/10.1016/j.biocon.2016.10.022)


## 2015
1.  Ohba S-Y\*, **Ushio M** (2015)  
    Effect of water depth on predation frequency by diving beetles on mosquito larvae prey. [_Entomological Science_ 18 (4):519–522](https://dx.doi.org/10.1111/ens.12143)
2.  **Ushio M**\*, Fujiki Y, Hidaka A, Kitayama K\*  (2015)  
    Linkage of root physiology and morphology as an adaptation to soil phosphorus impoverishment in tropical montane forests. [_Functional Ecology_ 29 (9):1235–1245](https://dx.doi.org/10.1111/1365-2435.12424) 
3.  Takasu H, **Ushio M**, LeClair JE, Nakano S-I\* (2015)  
    High contribution of _Synechococcus_ to phytoplankton biomass in the aphotic hypolimnion in a deep freshwater lake (Lake Biwa, Japan). [_Aquatic Microbial Ecology_ 75 (1):69–79](https://dx.doi.org/10.3354/ame01749) 
4.  **Ushio M**\*, Yamasaki E, Takasu H, Nagano AJ, Honjo MN, Fujinaga S, Ikemoto M, Sakai S, Kudoh H (2015)  
    Microbial communities on flower surfaces act as signatures of pollinator visitation. [_Scientific Reports_ 5: 8695](https://dx.doi.org/10.1038/srep08695)



## 2014
1.  Katayama N\*, Silva AO, Kishida O, **Ushio M**, Kita S, Ohgushi T (2014)  
    Herbivorous insect decreases plant nutrient uptake: the role of soil nutrient availability and association of below-ground symbionts. [_Ecological Entomology_ 39 (4):511–518]( https://dx.doi.org/10.1111/een.12125)
2.  **Ushio M**\*, Makoto K, Klaminder J, Takasu H, Nakano S-I (2014)  
    High-throughput sequencing shows inconsistent results with a microscope-based analysis of the soil prokaryotic community. [_Soil Biology & Biochemistry_ 76:53–56](https://dx.doi.org/10.1016/j.soilbio.2014.05.010)


## 2013
1.  **Ushio M**\*, Miki T, Balser TC (2013)  
    A coexisting fungal-bacterial community stabilizes soil decomposition activity in a microcosm experiment. [_PLoS ONE_ 8 (11) e80320](https://dx.plos.org/10.1371/journal.pone.0080320) 
2.  **Ushio M**\*, Makoto K, Klaminder J, Nakano S-I (2013)  
    CARD-FISH analysis of prokaryotic community composition and abundance along small-scale vegetation gradients in a dry arctic tundra ecosystem. [_Soil Biology & Biochemistry_ 64:147–154](https://dx.doi.org/10.1016/j.soilbio.2013.05.002)
3.  Nakazawa T\*, Ohba S-Y, **Ushio M** (2013)  
    Predator-prey body size relationships when predators can consume prey larger than themselves. [_Biology Letters_ 9 (3):20121193](https://dx.doi.org/10.1098/rsbl.2012.1193)
4.  **Ushio M**\*, Balser TC, Kitayama K (2013)  
    Effects of condensed tannins in conifer leaves on the composition and activity of soil microbial community in a tropical montane forest. [_Plant and Soil_ 365 (1–2):157–170](https://dx.doi.org/10.1007/s11104-012-1365-6)



## Before 2012
1.  Koyama K\*, Hidaka Y, **Ushio M** (2012)  
    Dynamic scaling in the growth of a non-branching plant, Cardiocrinum cordatum.  [_PLoS ONE_ 7 (9) e45317](https://dx.plos.org/10.1371/journal.pone.0045317) 
2.  **Ushio M**, Adams JM\* (2011)
    A meta-analysis of the global distribution pattern of condensed tannins in tree leaves.  [_The Open Ecology Journal_ 4:18–23](http://benthamopen.com/ABSTRACT/TOECOLJ-4-18)  
3.  Takeuchi Y, Salcher MM, **Ushio M**, Shimizu-Inatsugi R, Kobayashi MJ, Diway B, von Mering C, Pernthaler J, Shimizu KK\* (2011)  
    _In situ_ enzyme activity in the dissolved and particulate fraction of the fluid from four pitcher plant species of the genus _Nepenthes_. [_PLoS ONE_ 6 (9) e25144](https://dx.doi.org/10.1371/journal.pone.0025144)  
4.  **Ushio M**\*, Kitayama K, Balser TC (2010)  
    Tree species-mediated spatial patchiness of the composition of microbial community and physicochemical properties in the topsoils of a tropical montane forest. [_Soil Biology & Biochemistry_ 42 (9):1588–1595](https://dx.doi.org/10.1016/j.soilbio.2010.05.035)  
5.  Miki T\*, **Ushio M**, Fukui S, Kondoh M (2010)  
    Functional diversity of microbial decomposers facilitates plant coexistence in a plant-microbe-soil feedback model. [_PNAS_ 107 (32):14251–14256](https://dx.doi.org/10.1073/pnas.0914281107)
6.  **Ushio M**\*, Kitayama K, Balser TC (2010)
    Tree species effects on soil enzyme activities through effects on soil physicochemical and microbial properties in a tropical montane forest on Mt. Kinabalu, Borneo. [_Pedobiologia_ 53 (4):227–233](https://dx.doi.org/10.1016/j.pedobi.2009.12.003)
7.  **Ushio M**\*, Miki T, Kitayama K (2009)
    Phenolic control of plant nitrogen acquisition through the inhibition of soil microbial decomposition processes: A plant-microbe competition model. [_Microbes and Environments_ 24 (2):180–187](https://www.jstage.jst.go.jp/article/jsme2/24/2/24_ME09107/_article)
8.  **Ushio M**\*, Wagai R, Balser TC, Kitayama K (2008)
    Variations in the soil microbial community composition of a tropical montane forest ecosystem: Does tree species matter? [_Soil Biology & Biochemistry_ 40 (10):2699–2702](https://dx.doi.org/10.1016/j.soilbio.2008.06.023)

